- name: variables
  hosts: localhost
  vars:
    course: "Ansible"
    trainer: "Sagar"
    duration: "300hrs"
  tasks:
  vars :
  - name: "Varibales accessing"
    vars:
     course: "Devops"
     duration: "100hrs"
     trainer: "vinod"
    ansible.builtin.debug:
      msg: "Hi Iam learing {{course}} trainer is {{trainer}} duration is {{duration}}"
  - name: Overriding Access
    ansible.builtin.debug:
      msg: "Hi I am learning {{course}} trainer is {{trainer}} duration is {{duration}}"